### ISSUE TITLE
New version with DE features

### ISSUE THREAD

**Issue by fingolfon** [SiegeEngineers/WololoKingdoms#60] opened 2020-05-02 07:46 UTC
Hi. Firstly, thank you for your work. WK with UP 1.5 is still the most stable version of the game without significant bugs and pathfinding issues. I read that they will be a new version of the mod which supports some of the DE QOL features. Is there an estimated release date? And will the new version require owning the Definitive edition?

**Comment by AoE2CommunityGitHub** [comment] 2020-05-10 17:47
We're not currently planning on adding the new civilizations, but we will be adding various new features (queue-able technologies, auto-farm reseeding, villager counts in the UI, etc.).

> Is there an estimated release date?

Nothing more specific than "Soon". :)

> And will the new version require owning the Definitive edition?

No, the next update will just continue adding modifications to the current version. If a future update were to add the new civilizations, that would require owning DE to use those civilizations.

I'll close this issue as a duplicate of #54, which also asks about DE content in the upcoming update. Please write any other comments on that issue. :)

**Closed by AoE2CommunityGitHub** 2020-05-10 17:47 UTC
